import { openDB, IDBPDatabase } from 'idb';

// ============================================================================
// Types
// ============================================================================

export type MemoryDocumentType = 
  | 'image'           // User-uploaded image
  | 'pdf'             // User-uploaded PDF
  | 'training_plan'   // Generated by Training Plan module
  | 'insight'         // Generated by AI Insights module
  | 'note';           // User-created text note

export interface MemoryDocument {
  id: string;
  name: string;
  type: MemoryDocumentType;
  source: 'user' | 'system';
  mimeType: string;
  size: number;
  uploadedAt: Date;
  description?: string;
  extractedText?: string;
  tags?: string[];
  // For system documents (training plans, insights)
  content?: Record<string, unknown>;
  // Status for training plans
  status?: 'active' | 'archived';
}

export interface MemoryStore {
  documents: MemoryDocument[];
  totalSize: number;
  lastUpdated: Date;
}

// ============================================================================
// Constants
// ============================================================================

const DB_NAME = 'rowing_memory_db';
const DB_VERSION = 1;
const STORE_NAME = 'documents';
const BLOB_STORE_NAME = 'blobs';
const METADATA_KEY = 'rowing_memory_metadata';

export const MEMORY_CONFIG = {
  maxFileSize: 10 * 1024 * 1024,      // 10MB per file
  maxTotalStorage: 50 * 1024 * 1024,  // 50MB total
  supportedImageTypes: ['image/jpeg', 'image/png', 'image/gif', 'image/webp'],
  supportedPdfTypes: ['application/pdf'],
  smallFileSizeThreshold: 2 * 1024 * 1024, // 2MB - files smaller go to localStorage
} as const;

// ============================================================================
// Memory Storage Service
// ============================================================================

class MemoryStorageService {
  private static instance: MemoryStorageService;
  private db: IDBPDatabase | null = null;
  private initPromise: Promise<void> | null = null;

  private constructor() {}

  static getInstance(): MemoryStorageService {
    if (!MemoryStorageService.instance) {
      MemoryStorageService.instance = new MemoryStorageService();
    }
    return MemoryStorageService.instance;
  }

  // Initialize IndexedDB
  private async initDB(): Promise<void> {
    if (this.db) return;
    
    if (this.initPromise) {
      await this.initPromise;
      return;
    }

    this.initPromise = (async () => {
      try {
        this.db = await openDB(DB_NAME, DB_VERSION, {
          upgrade(db) {
            // Store for document metadata
            if (!db.objectStoreNames.contains(STORE_NAME)) {
              const store = db.createObjectStore(STORE_NAME, { keyPath: 'id' });
              store.createIndex('type', 'type');
              store.createIndex('source', 'source');
              store.createIndex('uploadedAt', 'uploadedAt');
            }
            // Store for large binary blobs
            if (!db.objectStoreNames.contains(BLOB_STORE_NAME)) {
              db.createObjectStore(BLOB_STORE_NAME);
            }
          },
        });
      } catch (error) {
        console.error('Failed to initialize IndexedDB:', error);
        throw error;
      }
    })();

    await this.initPromise;
  }

  // ============================================================================
  // Document CRUD Operations
  // ============================================================================

  async addDocument(
    file: File,
    options?: { description?: string; tags?: string[] }
  ): Promise<MemoryDocument> {
    await this.initDB();

    // Validate file
    const validation = this.validateFile(file);
    if (!validation.valid) {
      throw new Error(validation.error);
    }

    // Check storage quota
    const currentSize = await this.getTotalSize();
    if (currentSize + file.size > MEMORY_CONFIG.maxTotalStorage) {
      throw new Error(
        `Storage quota exceeded. Available: ${this.formatBytes(MEMORY_CONFIG.maxTotalStorage - currentSize)}`
      );
    }

    const id = this.generateId();
    const type = this.getDocumentType(file.type);
    const arrayBuffer = await file.arrayBuffer();

    const document: MemoryDocument = {
      id,
      name: file.name,
      type,
      source: 'user',
      mimeType: file.type,
      size: file.size,
      uploadedAt: new Date(),
      description: options?.description,
      tags: options?.tags,
    };

    // Store blob in IndexedDB
    if (this.db) {
      await this.db.put(BLOB_STORE_NAME, arrayBuffer, id);
      await this.db.put(STORE_NAME, document);
    }

    this.updateMetadata();
    return document;
  }

  async addSystemDocument(
    type: 'training_plan' | 'insight' | 'note',
    name: string,
    content: Record<string, unknown>,
    options?: { description?: string; status?: 'active' | 'archived' }
  ): Promise<MemoryDocument> {
    await this.initDB();

    // For training plans, archive existing active plans
    if (type === 'training_plan' && options?.status === 'active') {
      await this.archiveActivePlans();
    }

    const id = this.generateId();
    const contentString = JSON.stringify(content);

    const document: MemoryDocument = {
      id,
      name,
      type,
      source: 'system',
      mimeType: 'application/json',
      size: new Blob([contentString]).size,
      uploadedAt: new Date(),
      description: options?.description,
      content,
      status: options?.status,
      extractedText: contentString, // For searchability
    };

    if (this.db) {
      await this.db.put(STORE_NAME, document);
    }

    this.updateMetadata();
    return document;
  }

  async getDocument(id: string): Promise<MemoryDocument | null> {
    await this.initDB();
    if (!this.db) return null;

    const doc = await this.db.get(STORE_NAME, id);
    return doc ? this.deserializeDocument(doc) : null;
  }

  async getDocumentBlob(id: string): Promise<ArrayBuffer | null> {
    await this.initDB();
    if (!this.db) return null;

    return await this.db.get(BLOB_STORE_NAME, id);
  }

  async getAllDocuments(): Promise<MemoryDocument[]> {
    await this.initDB();
    if (!this.db) return [];

    const docs = await this.db.getAll(STORE_NAME);
    return docs.map(doc => this.deserializeDocument(doc));
  }

  async updateDocument(
    id: string,
    updates: Partial<Pick<MemoryDocument, 'name' | 'description' | 'tags' | 'status' | 'extractedText'>>
  ): Promise<MemoryDocument | null> {
    await this.initDB();
    if (!this.db) return null;

    const doc = await this.db.get(STORE_NAME, id);
    if (!doc) return null;

    const updatedDoc = { ...doc, ...updates };
    await this.db.put(STORE_NAME, updatedDoc);
    this.updateMetadata();

    return this.deserializeDocument(updatedDoc);
  }

  async deleteDocument(id: string): Promise<boolean> {
    await this.initDB();
    if (!this.db) return false;

    try {
      await this.db.delete(STORE_NAME, id);
      await this.db.delete(BLOB_STORE_NAME, id);
      this.updateMetadata();
      return true;
    } catch (error) {
      console.error('Failed to delete document:', error);
      return false;
    }
  }

  // ============================================================================
  // Query & Filter Operations
  // ============================================================================

  async searchDocuments(query: string): Promise<MemoryDocument[]> {
    const docs = await this.getAllDocuments();
    const lowerQuery = query.toLowerCase();

    return docs.filter(doc => 
      doc.name.toLowerCase().includes(lowerQuery) ||
      doc.description?.toLowerCase().includes(lowerQuery) ||
      doc.extractedText?.toLowerCase().includes(lowerQuery) ||
      doc.tags?.some(tag => tag.toLowerCase().includes(lowerQuery))
    );
  }

  async filterByType(type: MemoryDocumentType): Promise<MemoryDocument[]> {
    await this.initDB();
    if (!this.db) return [];

    const docs = await this.db.getAllFromIndex(STORE_NAME, 'type', type);
    return docs.map(doc => this.deserializeDocument(doc));
  }

  async filterBySource(source: 'user' | 'system'): Promise<MemoryDocument[]> {
    await this.initDB();
    if (!this.db) return [];

    const docs = await this.db.getAllFromIndex(STORE_NAME, 'source', source);
    return docs.map(doc => this.deserializeDocument(doc));
  }

  async getActiveTrainingPlan(): Promise<MemoryDocument | null> {
    const plans = await this.filterByType('training_plan');
    return plans.find(p => p.status === 'active') || null;
  }

  async getLatestInsight(): Promise<MemoryDocument | null> {
    const insights = await this.filterByType('insight');
    if (insights.length === 0) return null;

    return insights.sort((a, b) => 
      new Date(b.uploadedAt).getTime() - new Date(a.uploadedAt).getTime()
    )[0];
  }

  /**
   * Keep only the latest N insights in memory, deleting older ones.
   * Called automatically after adding a new insight.
   */
  async cleanupOldInsights(keepCount: number = 3): Promise<number> {
    const insights = await this.filterByType('insight');
    if (insights.length <= keepCount) return 0;

    // Sort by uploadedAt descending (newest first)
    const sorted = insights.sort((a, b) => 
      new Date(b.uploadedAt).getTime() - new Date(a.uploadedAt).getTime()
    );

    // Delete all but the newest `keepCount`
    const toDelete = sorted.slice(keepCount);
    let deletedCount = 0;

    for (const doc of toDelete) {
      const deleted = await this.deleteDocument(doc.id);
      if (deleted) deletedCount++;
    }

    return deletedCount;
  }

  // ============================================================================
  // Storage Management
  // ============================================================================

  async getTotalSize(): Promise<number> {
    const docs = await this.getAllDocuments();
    return docs.reduce((sum, doc) => sum + doc.size, 0);
  }

  async getRemainingQuota(): Promise<number> {
    const used = await this.getTotalSize();
    return MEMORY_CONFIG.maxTotalStorage - used;
  }

  async getStorageStats(): Promise<{
    totalSize: number;
    remainingQuota: number;
    documentCount: number;
    byType: Record<MemoryDocumentType, number>;
  }> {
    const docs = await this.getAllDocuments();
    const totalSize = docs.reduce((sum, doc) => sum + doc.size, 0);

    const byType: Record<MemoryDocumentType, number> = {
      image: 0,
      pdf: 0,
      training_plan: 0,
      insight: 0,
      note: 0,
    };

    docs.forEach(doc => {
      byType[doc.type]++;
    });

    return {
      totalSize,
      remainingQuota: MEMORY_CONFIG.maxTotalStorage - totalSize,
      documentCount: docs.length,
      byType,
    };
  }

  async clearAll(): Promise<void> {
    await this.initDB();
    if (!this.db) return;

    await this.db.clear(STORE_NAME);
    await this.db.clear(BLOB_STORE_NAME);
    this.updateMetadata();
  }

  // ============================================================================
  // Export / Import
  // ============================================================================

  async exportMemory(): Promise<Blob> {
    const docs = await this.getAllDocuments();
    const exportData: { documents: MemoryDocument[]; blobs: Record<string, string> } = {
      documents: docs,
      blobs: {},
    };

    // Export blobs as base64
    for (const doc of docs) {
      if (doc.source === 'user') {
        const blob = await this.getDocumentBlob(doc.id);
        if (blob) {
          exportData.blobs[doc.id] = this.arrayBufferToBase64(blob);
        }
      }
    }

    return new Blob([JSON.stringify(exportData)], { type: 'application/json' });
  }

  async importMemory(data: Blob): Promise<{ success: boolean; imported: number }> {
    try {
      const text = await data.text();
      const importData = JSON.parse(text);

      if (!importData.documents || !Array.isArray(importData.documents)) {
        throw new Error('Invalid import data format');
      }

      await this.initDB();
      if (!this.db) throw new Error('Database not initialized');

      let imported = 0;

      for (const doc of importData.documents) {
        // Skip if document already exists
        const existing = await this.db.get(STORE_NAME, doc.id);
        if (existing) continue;

        // Restore blob if available
        if (importData.blobs?.[doc.id]) {
          const blob = this.base64ToArrayBuffer(importData.blobs[doc.id]);
          await this.db.put(BLOB_STORE_NAME, blob, doc.id);
        }

        // Restore document
        await this.db.put(STORE_NAME, {
          ...doc,
          uploadedAt: new Date(doc.uploadedAt),
        });
        imported++;
      }

      this.updateMetadata();
      return { success: true, imported };
    } catch (error) {
      console.error('Failed to import memory:', error);
      return { success: false, imported: 0 };
    }
  }

  // ============================================================================
  // Private Helpers
  // ============================================================================

  private validateFile(file: File): { valid: boolean; error?: string } {
    const allSupportedTypes: readonly string[] = [
      ...MEMORY_CONFIG.supportedImageTypes,
      ...MEMORY_CONFIG.supportedPdfTypes,
    ];

    if (!allSupportedTypes.includes(file.type)) {
      return {
        valid: false,
        error: `Unsupported file type: ${file.type}. Supported: JPEG, PNG, GIF, WebP, PDF`,
      };
    }

    if (file.size > MEMORY_CONFIG.maxFileSize) {
      return {
        valid: false,
        error: `File too large: ${this.formatBytes(file.size)}. Maximum: ${this.formatBytes(MEMORY_CONFIG.maxFileSize)}`,
      };
    }

    return { valid: true };
  }

  private getDocumentType(mimeType: string): MemoryDocumentType {
    if ((MEMORY_CONFIG.supportedImageTypes as readonly string[]).includes(mimeType)) {
      return 'image';
    }
    if ((MEMORY_CONFIG.supportedPdfTypes as readonly string[]).includes(mimeType)) {
      return 'pdf';
    }
    return 'note';
  }

  private generateId(): string {
    return `mem_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
  }

  private deserializeDocument(doc: MemoryDocument): MemoryDocument {
    return {
      ...doc,
      uploadedAt: new Date(doc.uploadedAt),
    };
  }

  private async archiveActivePlans(): Promise<void> {
    const plans = await this.filterByType('training_plan');
    for (const plan of plans) {
      if (plan.status === 'active') {
        await this.updateDocument(plan.id, { status: 'archived' });
      }
    }
  }

  private updateMetadata(): void {
    if (typeof window === 'undefined' || typeof localStorage === 'undefined') return;
    
    localStorage.setItem(METADATA_KEY, JSON.stringify({
      lastUpdated: new Date().toISOString(),
    }));
  }

  private formatBytes(bytes: number): string {
    if (bytes === 0) return '0 Bytes';
    const k = 1024;
    const sizes = ['Bytes', 'KB', 'MB', 'GB'];
    const i = Math.floor(Math.log(bytes) / Math.log(k));
    return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i];
  }

  private arrayBufferToBase64(buffer: ArrayBuffer): string {
    const bytes = new Uint8Array(buffer);
    let binary = '';
    for (let i = 0; i < bytes.byteLength; i++) {
      binary += String.fromCharCode(bytes[i]);
    }
    return btoa(binary);
  }

  private base64ToArrayBuffer(base64: string): ArrayBuffer {
    const binary = atob(base64);
    const bytes = new Uint8Array(binary.length);
    for (let i = 0; i < binary.length; i++) {
      bytes[i] = binary.charCodeAt(i);
    }
    return bytes.buffer;
  }
}

// Export singleton instance
export const memoryStorage = MemoryStorageService.getInstance();
