// ============================================================================
// Types
// ============================================================================

export type MemoryDocumentType =
  | 'image'           // User-uploaded image
  | 'pdf'             // User-uploaded PDF
  | 'training_plan'   // Generated by Training Plan module
  | 'insight'         // Generated by AI Insights module
  | 'note';           // User-created text note

export interface MemoryDocument {
  id: string;
  name: string;
  type: MemoryDocumentType;
  source: 'user' | 'system';
  mimeType: string;
  size: number;
  filePath?: string;
  uploadedAt: Date;
  description?: string;
  extractedText?: string;
  tags?: string[];
  // For system documents (training plans, insights)
  content?: Record<string, unknown>;
  // Status for training plans
  status?: 'active' | 'archived';
}

export interface MemoryStore {
  documents: MemoryDocument[];
  totalSize: number;
  lastUpdated: Date;
}

// ============================================================================
// Constants
// ============================================================================

export const MEMORY_CONFIG = {
  maxFileSize: 10 * 1024 * 1024,      // 10MB per file
  maxTotalStorage: 50 * 1024 * 1024,  // 50MB total
  supportedImageTypes: ['image/jpeg', 'image/png', 'image/gif', 'image/webp'],
  supportedPdfTypes: ['application/pdf'],
  smallFileSizeThreshold: 2 * 1024 * 1024, // 2MB - files smaller go to localStorage
} as const;

// ============================================================================
// Memory Storage Service (DB-backed)
// ============================================================================

class MemoryStorageService {
  private static instance: MemoryStorageService;

  private constructor() { }

  static getInstance(): MemoryStorageService {
    if (!MemoryStorageService.instance) {
      MemoryStorageService.instance = new MemoryStorageService();
    }
    return MemoryStorageService.instance;
  }

  private async fetchDocumentsFromDB(): Promise<MemoryDocument[]> {
    const res = await fetch('/api/memory');
    if (!res.ok) {
      const data = await res.json().catch(() => null);
      throw new Error(data?.error || 'Failed to fetch memory documents');
    }
    const data = await res.json();
    const docs = (data.documents || []) as MemoryDocument[];
    return docs.map((d) => this.deserializeDocument(d));
  }

  // ============================================================================
  // Document CRUD Operations
  // ============================================================================

  async addDocument(
    file: File,
    options?: { description?: string; tags?: string[] }
  ): Promise<MemoryDocument> {
    // Validate file
    const validation = this.validateFile(file);
    if (!validation.valid) {
      throw new Error(validation.error);
    }

    const form = new FormData();
    form.set('file', file);
    if (options?.description) form.set('description', options.description);
    if (options?.tags?.length) form.set('tags', options.tags.join(','));
    form.set('uploadedAt', new Date().toISOString());

    const res = await fetch('/api/memory/upload', {
      method: 'POST',
      body: form,
    });

    if (!res.ok) {
      const data = await res.json().catch(() => null);
      throw new Error(data?.error || 'Failed to upload document');
    }

    const data = await res.json();
    return this.deserializeDocument(data.document as MemoryDocument);
  }

  async addSystemDocument(
    type: 'training_plan' | 'insight' | 'note',
    name: string,
    content: Record<string, unknown>,
    options?: { description?: string; status?: 'active' | 'archived' }
  ): Promise<MemoryDocument> {
    // Deduplicate: Remove existing documents with same internal keys to ensure uniquely relevant sets
    const existingDocs = await this.filterByType(type);

    const contentId = (content as any)?.id;
    const generatedAt = (content as any)?.generatedAt;

    const duplicates = existingDocs.filter(doc => {
      // 1. Training Plan Check: Match by internal content ID
      if (type === 'training_plan' && contentId) {
        const docContentId = (doc.content as any)?.id;
        if (docContentId && contentId === docContentId) {
          return true;
        }
      }

      // 2. Insight Check: Match by Name AND GeneratedAt
      // This allows multiple differently-timed insights on the same day, but prevents exact duplicates
      if (type === 'insight' && generatedAt) {
        const docGeneratedAt = (doc.content as any)?.generatedAt;
        if (docGeneratedAt && name === doc.name && generatedAt === docGeneratedAt) {
          return true;
        }
      }

      // No fallback generic name check for other types as requested
      return false;
    });

    for (const doc of duplicates) {
      await this.deleteDocument(doc.id);
    }

    // For training plans, archive existing active plans
    if (type === 'training_plan' && options?.status === 'active') {
      await this.archiveActivePlans();
    }

    const contentString = JSON.stringify(content);
    const uploadedAt = new Date();

    const res = await fetch('/api/memory', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        documents: [
          {
            name,
            type,
            source: 'system',
            mimeType: 'application/json',
            size: new Blob([contentString]).size,
            description: options?.description,
            tags: [],
            content,
            status: options?.status,
            extractedText: contentString,
            uploadedAt: uploadedAt.toISOString(),
          },
        ],
      }),
    });

    if (!res.ok) {
      const data = await res.json().catch(() => null);
      throw new Error(data?.error || 'Failed to save system document');
    }

    const data = await res.json();
    const docs = (data.documents || []) as MemoryDocument[];
    if (docs.length === 0) {
      throw new Error('Failed to save system document');
    }

    return this.deserializeDocument(docs[0]);
  }

  async getDocument(id: string): Promise<MemoryDocument | null> {
    const docs = await this.fetchDocumentsFromDB();
    return docs.find((d: MemoryDocument) => d.id === id) || null;
  }

  async getDocumentBlob(id: string): Promise<ArrayBuffer | null> {
    const res = await fetch(`/api/memory/file?documentId=${encodeURIComponent(id)}`);
    if (!res.ok) {
      return null;
    }
    return await res.arrayBuffer();
  }

  async getAllDocuments(): Promise<MemoryDocument[]> {
    return await this.fetchDocumentsFromDB();
  }

  async updateDocument(
    id: string,
    updates: Partial<Pick<MemoryDocument, 'name' | 'description' | 'tags' | 'status' | 'extractedText'>>
  ): Promise<MemoryDocument | null> {
    const res = await fetch('/api/memory', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        documents: [{ id, ...updates }],
      }),
    });

    if (!res.ok) {
      return null;
    }

    const data = await res.json();
    const docs = (data.documents || []) as MemoryDocument[];
    return docs.length > 0 ? this.deserializeDocument(docs[0]) : null;
  }

  async deleteDocument(id: string): Promise<boolean> {
    try {
      const res = await fetch('/api/memory', {
        method: 'DELETE',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ documentId: id }),
      });
      return res.ok;
    } catch (error) {
      console.error('Failed to delete document:', error);
      return false;
    }
  }

  // ============================================================================
  // Query & Filter Operations
  // ============================================================================

  async searchDocuments(query: string): Promise<MemoryDocument[]> {
    const docs = await this.getAllDocuments();
    const lowerQuery = query.toLowerCase();

    return docs.filter(doc =>
      doc.name.toLowerCase().includes(lowerQuery) ||
      doc.description?.toLowerCase().includes(lowerQuery) ||
      doc.extractedText?.toLowerCase().includes(lowerQuery) ||
      doc.tags?.some(tag => tag.toLowerCase().includes(lowerQuery))
    );
  }

  async filterByType(type: MemoryDocumentType): Promise<MemoryDocument[]> {
    const docs = await this.fetchDocumentsFromDB();
    return docs.filter(d => d.type === type);
  }

  async filterBySource(source: 'user' | 'system'): Promise<MemoryDocument[]> {
    const docs = await this.fetchDocumentsFromDB();
    return docs.filter(d => d.source === source);
  }

  async getActiveTrainingPlan(): Promise<MemoryDocument | null> {
    const plans = await this.filterByType('training_plan');
    return plans.find(p => p.status === 'active') || null;
  }

  async getLatestInsight(): Promise<MemoryDocument | null> {
    const insights = await this.filterByType('insight');
    if (insights.length === 0) return null;

    return insights.sort((a, b) =>
      new Date(b.uploadedAt).getTime() - new Date(a.uploadedAt).getTime()
    )[0];
  }

  /**
   * Check if a training plan memory document is orphaned (no longer exists in trainingPlans storage).
   * Returns the plan ID if found in content, or null if not a training plan.
   */
  getTrainingPlanId(doc: MemoryDocument): string | null {
    if (doc.type !== 'training_plan') return null;
    return (doc.content as { planId?: string })?.planId || null;
  }

  /**
   * Check if an insight memory document is orphaned.
   * Returns the insight IDs if found in content, or null if not an insight.
   */
  getInsightIds(doc: MemoryDocument): string[] | null {
    if (doc.type !== 'insight') return null;
    const content = doc.content as { insights?: Array<{ id?: string }> };
    if (!content?.insights) return null;
    return content.insights.map(i => i.id).filter((id): id is string => !!id);
  }

  /**
   * Keep only the latest N insights in memory, deleting older ones.
   * Called automatically after adding a new insight.
   */
  async cleanupOldInsights(keepCount: number = 3): Promise<number> {
    const insights = await this.filterByType('insight');
    if (insights.length <= keepCount) return 0;

    // Filter to ensure we ONLY delete system-generated insights
    // This protects user-uploaded documents that might be mislabeled or have type 'insight'
    const systemInsights = insights.filter(doc => doc.source === 'system');

    // Sort by uploadedAt descending (newest first)
    const sorted = systemInsights.sort((a, b) =>
      new Date(b.uploadedAt).getTime() - new Date(a.uploadedAt).getTime()
    );

    // If we have fewer system insights than the keep limit, don't delete anything
    if (sorted.length <= keepCount) return 0;

    // Delete all but the newest `keepCount`
    const toDelete = sorted.slice(keepCount);
    let deletedCount = 0;

    for (const doc of toDelete) {
      const deleted = await this.deleteDocument(doc.id);
      if (deleted) deletedCount++;
    }

    return deletedCount;
  }

  // ============================================================================
  // Storage Management
  // ============================================================================

  async getTotalSize(): Promise<number> {
    const docs = await this.getAllDocuments();
    return docs.reduce((sum, doc) => sum + doc.size, 0);
  }

  async getRemainingQuota(): Promise<number> {
    const used = await this.getTotalSize();
    return MEMORY_CONFIG.maxTotalStorage - used;
  }

  async getStorageStats(): Promise<{
    totalSize: number;
    remainingQuota: number;
    documentCount: number;
    byType: Record<MemoryDocumentType, number>;
  }> {
    const docs = await this.getAllDocuments();
    const totalSize = docs.reduce((sum, doc) => sum + doc.size, 0);

    const byType: Record<MemoryDocumentType, number> = {
      image: 0,
      pdf: 0,
      training_plan: 0,
      insight: 0,
      note: 0,
    };

    docs.forEach(doc => {
      byType[doc.type]++;
    });

    return {
      totalSize,
      remainingQuota: MEMORY_CONFIG.maxTotalStorage - totalSize,
      documentCount: docs.length,
      byType,
    };
  }

  async clearAll(): Promise<void> {
    // DB is source of truth; clear via API
    const docs = await this.getAllDocuments();
    for (const d of docs) {
      await this.deleteDocument(d.id);
    }
  }

  // ============================================================================
  // Export / Import
  // ============================================================================

  async exportMemory(): Promise<Blob> {
    const docs = await this.getAllDocuments();
    const exportData: { documents: MemoryDocument[]; blobs: Record<string, string> } = {
      documents: docs,
      blobs: {},
    };

    // Export blobs as base64
    for (const doc of docs) {
      if (doc.source === 'user') {
        const blob = await this.getDocumentBlob(doc.id);
        if (blob) {
          exportData.blobs[doc.id] = this.arrayBufferToBase64(blob);
        }
      }
    }

    return new Blob([JSON.stringify(exportData)], { type: 'application/json' });
  }

  async importMemory(data: Blob): Promise<{ success: boolean; imported: number }> {
    try {
      const text = await data.text();
      const importData = JSON.parse(text);

      if (!importData.documents || !Array.isArray(importData.documents)) {
        throw new Error('Invalid import data format');
      }

      // Get existing documents to avoid duplicates
      const existingDocs = await this.fetchDocumentsFromDB();
      const existingIds = new Set(existingDocs.map(d => d.id));

      let imported = 0;

      for (const doc of importData.documents) {
        // Skip if document already exists
        if (existingIds.has(doc.id)) continue;

        // For user documents with blobs, we need to upload via the upload API
        if (doc.source === 'user' && importData.blobs?.[doc.id]) {
          const blobData = this.base64ToArrayBuffer(importData.blobs[doc.id]);
          const file = new File([blobData], doc.name, { type: doc.mimeType });

          try {
            await this.addDocument(file, {
              description: doc.description,
              tags: doc.tags,
            });
            imported++;
          } catch (error) {
            console.warn(`Failed to import document ${doc.name}:`, error);
          }
        } else {
          // For system documents, use the standard API
          const res = await fetch('/api/memory', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
              documents: [{
                ...doc,
                uploadedAt: doc.uploadedAt,
              }],
            }),
          });

          if (res.ok) {
            imported++;
          }
        }
      }

      return { success: true, imported };
    } catch (error) {
      console.error('Failed to import memory:', error);
      return { success: false, imported: 0 };
    }
  }

  // ============================================================================
  // Private Helpers
  // ============================================================================

  private validateFile(file: File): { valid: boolean; error?: string } {
    const allSupportedTypes: readonly string[] = [
      ...MEMORY_CONFIG.supportedImageTypes,
      ...MEMORY_CONFIG.supportedPdfTypes,
    ];

    if (!allSupportedTypes.includes(file.type)) {
      return {
        valid: false,
        error: `Unsupported file type: ${file.type}. Supported: JPEG, PNG, GIF, WebP, PDF`,
      };
    }

    if (file.size > MEMORY_CONFIG.maxFileSize) {
      return {
        valid: false,
        error: `File too large: ${this.formatBytes(file.size)}. Maximum: ${this.formatBytes(MEMORY_CONFIG.maxFileSize)}`,
      };
    }

    return { valid: true };
  }

  private deserializeDocument(doc: MemoryDocument): MemoryDocument {
    return {
      ...doc,
      uploadedAt: new Date(doc.uploadedAt),
    };
  }

  private async archiveActivePlans(): Promise<void> {
    const plans = await this.filterByType('training_plan');
    for (const plan of plans) {
      if (plan.status === 'active') {
        await this.updateDocument(plan.id, { status: 'archived' });
      }
    }
  }

  private formatBytes(bytes: number): string {
    if (bytes === 0) return '0 Bytes';
    const k = 1024;
    const sizes = ['Bytes', 'KB', 'MB', 'GB'];
    const i = Math.floor(Math.log(bytes) / Math.log(k));
    return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i];
  }

  private arrayBufferToBase64(buffer: ArrayBuffer): string {
    const bytes = new Uint8Array(buffer);
    let binary = '';
    for (let i = 0; i < bytes.byteLength; i++) {
      binary += String.fromCharCode(bytes[i]);
    }
    return btoa(binary);
  }

  private base64ToArrayBuffer(base64: string): ArrayBuffer {
    const binary = atob(base64);
    const bytes = new Uint8Array(binary.length);
    for (let i = 0; i < binary.length; i++) {
      bytes[i] = binary.charCodeAt(i);
    }
    return bytes.buffer;
  }
}

// Export singleton instance
export const memoryStorage = MemoryStorageService.getInstance();
